site_name: CID Documentation
site_description: Documentation of github.com/cidverse
use_directory_urls: true

repo_url: https://github.com/cidverse/cid
edit_uri: https://github.com/cidverse/cidverse.github.io/edit/main/docs

theme:
  locale: en
  name: material
  font: false
  # light / dark mode
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - content.tabs.link

nav:
  - index.md
  - CID:
      - cid/index.md
      - Usage:
        - cid/usage/local.md
        - cid/usage/githubactions.md
        - cid/usage/gitlab.md
      - Config:
        - cid/config/workflow.md
        - cid/config/repository.md
        - cid/config/action.md
      - cid/enterprise.md
      - Actions:
        - cid/extension/action.md
        - cid/extension/rules.md
        - cid/extension/sdk-go.md
        - cid/extension/sdk-java.md
        - cid/extension/sdk-kotlin.md
        - cid/extension/sdk-python.md
  - CID Catalog:
    - cid/catalog/action-reference.md
    - Workflows:
        - cid/catalog/workflows/index.md
        - cid/catalog/workflows/main.md
    - Actions:
      - cid/catalog/actions/index.md
      - cid/catalog/actions/applicationinspector-scan.md
      - cid/catalog/actions/buildah-build.md
      - cid/catalog/actions/buildah-publish.md
      - cid/catalog/actions/changelog-generate.md
      - cid/catalog/actions/cosign-container-sbom-attach.md
      - cid/catalog/actions/cosign-container-sign.md
      - cid/catalog/actions/gitguardian-scan.md
      - cid/catalog/actions/github-release-publish.md
      - cid/catalog/actions/github-sarif-upload.md
      - cid/catalog/actions/gitlab-release-publish.md
      - cid/catalog/actions/gitleaks-scan.md
      - cid/catalog/actions/go-build.md
      - cid/catalog/actions/go-lint.md
      - cid/catalog/actions/go-test.md
      - cid/catalog/actions/gosec-scan.md
      - cid/catalog/actions/helm-build.md
      - cid/catalog/actions/helm-lint.md
      - cid/catalog/actions/helm-publish-nexus.md
      - cid/catalog/actions/helm-publish-registry.md
      - cid/catalog/actions/hugo-build.md
      - cid/catalog/actions/java-build.md
      - cid/catalog/actions/java-publish.md
      - cid/catalog/actions/java-test.md
      - cid/catalog/actions/mkdocs-build.md
      - cid/catalog/actions/node-build.md
      - cid/catalog/actions/node-test.md
      - cid/catalog/actions/ossf-scorecard-scan.md
      - cid/catalog/actions/python-build.md
      - cid/catalog/actions/python-lint.md
      - cid/catalog/actions/python-test.md
      - cid/catalog/actions/qodana-scan.md
      - cid/catalog/actions/semgrep-scan.md
      - cid/catalog/actions/sonarqube-scan.md
      - cid/catalog/actions/syft-artifact-sbom-generate.md
      - cid/catalog/actions/syft-container-sbom-generate.md
      - cid/catalog/actions/techdocs-build.md
      - cid/catalog/actions/techdocs-publish.md
      - cid/catalog/actions/upx-optimize.md
  - NormalizeCI:
      - normalizeci/index.md
      - normalizeci/spec.md
      - Usage:
        - normalizeci/usage/cli.md
        - normalizeci/usage/library.md
      - Platform:
        - normalizeci/platform/generic-git.md
        - normalizeci/platform/azuredevops.md
        - normalizeci/platform/githubactions.md
        - normalizeci/platform/gitlabci.md
  - Repository Analyzer:
      - repoanalyzer/index.md
  - Container Images:
      - container-images/index.md
      - container-images/cli-image.md
      - container-images/base-image.md
  - Development:
      - development/overview.md
      - development/pullrequest.md
      - Conventions:
        - development/convention/commits.md
        - development/convention/versioning.md
      - Guides:
        - development/guide/github.md
        - development/guide/gitlab.md
        - development/guide/renovate.md
        - development/guide/sonarcloud.md
  - Contribution:
      - contribution/index.md
      - contribution/coc.md

markdown_extensions:
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/content.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cidverse/cid
      name: GitHub
