# name
name: CI

# triggers
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

# default permissions
permissions:
  contents: read

# jobs
jobs:
  # build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
        with:
          version: experimental
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: |
          cid workflow run --stage build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .dist/cidverse-github-io/html
  # publish
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
